name: anker1209-sync
on:
  push:
      branches:
        - main
  schedule:
    # 格林威治时间 (GMT) 每日01时开始执行
    - cron: '0 1 * * *'
  workflow_dispatch:
  watch:
    types: started
  repository_dispatch:
    types: sync-anker1209/Scriptable
jobs:
  repo-sync:
    env:
      PAT: ${{ secrets.PAT }} 
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: sync anker1209/Scriptable
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/anker1209/Scriptable.git"
          source_branch: "main"
          destination_branch: "anker1209"
          github_token: ${{ secrets.PAT }}
