name: Auto master
on:
  schedule:
    - cron: '* * * * *'
  workflow_dispatch:
  watch:
    types: started
  repository_dispatch:
    types: anker1209-Scriptable # 上游作者库名
jobs:
  repo-sync:
    env:
      PAT: ${{ secrets.PAT }} 
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: sync anker1209-Scriptable  # 需要同步的作者库名
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/anker1209/Scriptable.git" # 需要 clone 的上游仓库地址 
          source_branch: "main" # 需要clone上游作者的分支名
          destination_branch: "main" # 需要clone到自己项目的分支名
          github_token: ${{ secrets.PAT }}