name: Auto Merge

on:
  push:
    branches:
      -main
  schedule:
     - cron: '*/1 * * * *'

jobs:
  update_external_airflow_fork:
    runs-on: ubuntu-latest
    steps:
      - uses: Semporia/github-forks-sync-action@master
        with:
          github_token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }} # 令牌
          upstream_repository: anker1209/Scriptable  # 上游仓库
          target_repository: Semporia/Scriptable  # 你要推送的仓库
          upstream_branch: main  # 默认是拉取上游仓库的main分支
          target_branch: main  # 默认推送到你的仓库main分支
          force: true  # 是否强制推送
          tags: true  # 确定是否使用-tags
